swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "Chaman"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "chaman.frol.be"
basePath: "/api"
tags:
  - name: "field"
    description: "Field information"
  - name: "template"
    description: "Template information"
  - name: "item"
    description: "complete item form"
schemes:
  - "https"
  - "http"

paths:
  /field:
    get:
      tags:
        - "field"
      summary: "Get a field"
      description: ""
      operationId: "getField"
      produces:
        - "application/json"
      responses:
        "200":
          description: "OK"
          schema:
            type: array
            items:
              $ref: "#/definitions/Field"
    post:
      tags:
        - "field"
      summary: "create a field"
      description: ""
      operationId: "createField"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "field"
          required: true
          schema:
            $ref : "#/definitions/Field"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/Field"

  /field/{uuid}:
    put:
      tags:
        - "field"
      summary: "update a field"
      description: ""
      operationId: "updateField"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "uuid"
          required: true
          type: string
        - in: "body"
          name: "field"
          required: true
          schema:
            $ref : "#/definitions/Field"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/Field"

  /data-types/:
    get:
      tags:
        - "datatypes"
      summary: "get data type"
      description: ""
      operationId: "getDataTypes"
      produces:
        - "application/json"
      responses:
        "200":
          description: "OK"
          schema:
            type: array
            items:
              $ref: "#/definitions/FieldType"

  /template:
    get:
      tags:
        - "template"
      summary: "Get all templates"
      description: ""
      operationId: "getTemplates"
      produces:
        - "application/json"
      responses:
        "200":
          description: "OK"
          schema:
            type: array
            items:
              $ref: "#/definitions/Template"
    post:
      tags:
        - "template"
      summary: "create a template"
      description: ""
      operationId: "createTemplate"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "template"
          required: true
          schema:
            $ref : "#/definitions/Template"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/Template"

  /template/{uuid}:
    get:
      tags:
        - "template"
      summary: "get a template"
      description: ""
      operationId: "getTemplate"
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "uuid"
          required: true
          type: string
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/Template"
    put:
      tags:
        - "template"
      summary: "update a template"
      description: ""
      operationId: "updateTemplate"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "uuid"
          required: true
          type: string
        - in: "body"
          name: "template"
          required: true
          schema:
            $ref : "#/definitions/Template"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/Template"

definitions:
  FieldType:
    type: "object"
    required:
      - identifier
    properties:
      identifier:
        type: "string"

  Field:
    type: "object"
    properties:
      uuid:
        type: "string"
        description: "single uuid acrross all version of the field"
      label:
        type: "string"
      reference:
        type: "string"
      dataType:
        type: "string"
      value:
        description: "value of the type"
      valueOrigin:
        type: string


  Template:
    type: "object"
    properties:
      uuid:
        type: string
      parents:
        type: array
        items:
          $ref: "#/definitions/Template"
      label:
        type: "string"
      reference:
        type: "string"
      content:
        type: array
        items:
          $ref: "#/definitions/Field"

