openapi: 3.0.1
info:
  title: Chaman
  description: ""
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: https://chaman.frol.be/api
  - url: http://chaman.frol.be/api
tags:
  - name: field
    description: Field information
  - name: item
    description: complete item form
paths:

  /field:
    get:
      tags:
        - field
      summary: Get a field
      operationId: getField
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Field'
    post:
      tags:
        - field
      summary: create a field
      operationId: createField
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FieldConfig'
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Field'

  /field/{uuid}:
    get:
      tags:
        - field
      summary: get a field config
      operationId: getFieldConfig
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FieldConfig'
    put:
      tags:
        - field
      summary: update a field
      operationId: updateField
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FieldConfig'
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Field'
    delete:
      tags:
        - field
      summary: delete a field
      operationId: deleteField
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content: {}
  /data-types/:
    get:
      tags:
        - datatypes
      summary: get data type
      operationId: getDataTypes
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FieldConfig'
  /item:
    get:
      tags:
        - item
      summary: Get all items
      operationId: getItems
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
    post:
      tags:
        - item
      summary: create an item
      operationId: createItem
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'

  /item/{uuid}:
    get:
      tags:
        - item
      summary: get a item
      operationId: getItem
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
    put:
      tags:
        - item
      summary: update a item
      operationId: updateItem
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'

    delete:
      tags:
        - item
      summary: delete a item
      operationId: deleteItem
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content: {}
components:
  schemas:
    FieldType:
      required:
        - identifier
      type: object
      properties:
        identifier:
          type: string

    Field:
      type: object
      properties:
        uuid:
          type: string
          description: single uuid acrross all version of the field
        label:
          type: string
        reference:
          type: string
        inputType:
          type: string
        value:
          type: array
          items:
            $ref: '#/components/schemas/FieldValue'
        params: {}
        errorMessages:
          type: array
          items:
            type: string

    FieldConfig:
      type: object
      properties:
        label:
          type: string
        reference:
          type: string
        datatype:
          type: string
        config:
          type: array
          items:
            $ref: '#/components/schemas/Field'


    FieldValue:
      type: object
      properties:
        uuid:
          type: string
          description: identifier of the value
        value: {}
    Item:
      type: object
      properties:
        uuid:
          type: string
        title:
          type: string
        description:
          type: string
        content:
          type: array
          items:
            $ref: '#/components/schemas/Field'
