version: "2"

services:

  back:
    build: ./back
    volumes:
      - $HOME:/var/home/:rw
      - ..:/src
    user: $UID
    working_dir: /src/back
    ports:
      - 9000:9000
    command: ["run"]
    stdin_open: true

  front:
    build: ./front
    ports:
      - 80:4200
    volumes: 
      - ../front:/src
    user: $UID
    command: sh -c "npm install && ng serve --proxy-config /src/src/environments/docker.proxy.json --host 0.0.0.0 --disable-host-check"

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=chaman
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass

  keycloak:
    image: quay.io/keycloak/keycloak:15.0.2
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_USER=chaman
      - KEYCLOAK_PASSWORD=pwd
      - KEYCLOAK_FRONTEND_URL=http://keycloak:8080/auth
      - DB_VENDOR=mysql
      - DB_ADDR=db
      - DB_USER=user
      - DB_PASSWORD=pass
      - DB_DATABASE=chaman
